[project]
org-name= "celleryio"
version= "0.3.1"

[dependencies]

[platform]
target = "java8"

  [[platform.libraries]]
  module = "cellery"
  path = "./cellery-utils/target/cellery-utils-0.4.0.jar"
  artafactId = "cellery-utils"
  version = "0.4.0"
  groupId = "io.cellery"

  [[platform.libraries]]
  module = "json"
  path = "./cellery-utils/target/classes/lib/json-20180813.jar"
  artafactId = "json"
  version = "20180813"
  groupId = "org.json"

  [[platform.libraries]]
  module = "kubernetes-client"
  path = "./cellery-utils/target/classes/lib/kubernetes-client-4.3.0.jar"
  artafactId = "kubernetes-client"
  version = "4.3.0"
  groupId = "io.fabric8"