[project]
org-name= "celleryio"
version= "0.3.1"

[dependencies]

[platform]
target = "java8"

  [[platform.libraries]]
  module = "cellery"
  path = "./cellery-utils/target/cellery-utils-0.4.0.jar"
  artafactId = "cellery-utils"
  version = "0.4.0"
  groupId = "io.cellery"

  [[platform.libraries]]
  module = "json"
  path = "./cellery-utils/target/classes/lib/json-20190722.jar"
  artafactId = "javax.jms-api"
  version = "2.0.1"
  groupId = "javax.jms"